WebClient/Controllers/Admin/ManageUserController.cs
using Business.Models;
using DataAccess.DAO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebClient2.Controllers.Admin
{
    [Authorize(Roles = "Admin")]
    public class ManageUserController : Controller
    {
        public IActionResult ViewUser()
        {
            List<Account> accounts = AccountDAO.GetAllAccount();
            ViewBag.Accounts = accounts;
            return View();
        }

        public IActionResult UserDetail(int userId)
        {
            Account account = AccountDAO.GetAccountWithId(userId);

            ViewBag.Account = account;
            return View(account);
        }

        [HttpPost]
        public IActionResult DeleteAccount(int userId)
        {
            AccountDAO.DeleteAccount(userId);
            return Json(new { success = true });
        }

        public IActionResult SearchByUsername(string username)
        {
            // Thực hiện tìm kiếm theo tên người dùng
            List<Account> result = AccountDAO.GetAccountWithUsername(username);

            // Trả về kết quả dưới dạng JSON
            return Json(result);
        }
    }
}

WebClient/Controllers/WalletController.cs
using Business.Models;
using DataAccess.DAO;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace WebClient2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class WalletController : Controller
    {
        public IActionResult SearchByName(string username)
        {
            return View();
        }
        #region WALLET
        public ActionResult Index()
        {
            ViewBag.accountId = HttpContext.Session.GetInt32("Account");
            List<Wallet> wallets = new List<Wallet>();
            wallets = WalletDAO.GetAllWallet();
            ViewBag.Wallets = wallets;
            return View();
        }

        public ActionResult WalletDetail(int userId)
        {
            ViewBag.accountId = HttpContext.Session.GetInt32("Account");
            Wallet wallet = new Wallet();
            wallet = WalletDAO.GetWalletByAccountId(userId);
            ViewBag.Wallet = wallet;
            return View();
        }
        #endregion

        #region WITHDRAWAL
        public ActionResult WithdrawalTransaction()
        {
            ViewBag.accountId = HttpContext.Session.GetInt32("Account");
            List<Withdrawal> withdrawals = new List<Withdrawal>();
            withdrawals = WithdrawalDAO.GetAllWithdrawal();
            ViewBag.Withdrawals = withdrawals;
            return View();
        }

        public ActionResult WithdrawalDetail(int withdrawal_id)
        {
            ViewBag.accountId = HttpContext.Session.GetInt32("Account");
            Withdrawal withdrawal = new Withdrawal();
            withdrawal = WithdrawalDAO.GetWithdrawalById(withdrawal_id);
            ViewBag.Withdrawal = withdrawal;
            return View();
        }

        [HttpPost]
        public ActionResult WithdrawalHandle(int withdrawal_id, string status)
        {
            Withdrawal withdrawal = new Withdrawal();
            withdrawal = WithdrawalDAO.GetWithdrawalById(withdrawal_id);
            if (WalletDAO.GetWalletById(withdrawal.wallet_id).balance >= (withdrawal.amount))
            {
             
                withdrawal.status = status;
                WithdrawalDAO.UpdateWithdrawal(withdrawal);

                return RedirectToAction("WithdrawalDetail", new { withdrawal_id = withdrawal_id });
            }
            else
            {
                return RedirectToAction("WithdrawalDetail", new { withdrawal_id = withdrawal_id });
            }
          
        }

        #endregion
        #region DEPOSIT
        public ActionResult DepositTransaction()
        {
            ViewBag.accountId = HttpContext.Session.GetInt32("Account");
            List<Deposit> deposits = new List<Deposit>();
            deposits = DepositDAO.GetAllDeposit();
            ViewBag.Deposits = deposits;
            return View();
        }

        [HttpGet]
        public ActionResult DepositDetail(int deposit_id)
        {
            ViewBag.accountId = HttpContext.Session.GetInt32("Account");
            Deposit deposit = new Deposit();
            deposit = DepositDAO.GetDepositById(deposit_id);
            ViewBag.Deposit = deposit;
            return View();
        }

        [HttpPost]
        public ActionResult DepositHandle(int deposit_id, string status)
        {
            Deposit deposit = new Deposit();
            deposit = DepositDAO.GetDepositById(deposit_id);
 
            deposit.status = status;
            DepositDAO.UpdateDeposit(deposit);

            return RedirectToAction("DepositDetail", new { deposit_id = deposit_id });
        }
        #endregion

 

  
    }
}

WebClient/Views/Admin/Index.cshtml
@using WebClient2
@using WebClient2.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trade&Deal Hub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Home/Index.css" asp-append-version="true" />
</head>
<body>
    <header>
        <marquee behavior="scroll" direction="left"><h6 style="color: red;">Thông báo: Đây là trang dành riêng cho ADMIN</h6></marquee>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trade&Deal Hub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Profile">ProfileA</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ManageUser" asp-action="ViewUser">Manager</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wallet" asp-action="Index">Wallet</a>
                        </li>

                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (ViewBag.accountId == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown nav-item"><a aria-haspopup="true" href="#" class="nav-link" aria-expanded="false"><i class="fa-regular fa-bell" style="color:black;"></i></a></li>
                            <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                            </li>
                            </li>
                        }
                    </ul>
                     <ul class="navbar-nav ml-auto">
                        @if (ViewBag.accountId == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown nav-item"><a aria-haspopup="true" href="#" class="nav-link" aria-expanded="false"><i class="fa-regular fa-bell" style="color:black;"></i></a></li>
                            <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                            </li>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav ml-auto">
                        @if (ViewBag.accountId == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="dropdown nav-item"><a aria-haspopup="true" href="#" class="nav-link" aria-expanded="false"><i class="fa-regular fa-bell" style="color:black;"></i></a></li>
                            <li class="nav-item">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                            </li>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <div class="text-center">
                <h1 class="display-4">Welcome Admin</h1>
                <h1 class="display-4">This Page need admin role</h1>
                <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Trade&Deal Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

WebClient/Views/Admin/ProfileAdmin.cshtml
@using Business.Models;
@using DataAccess.DAO;
@using WebClient2
@using WebClient2.Models
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Trade&Deal Hub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Home/Index.css" asp-append-version="true" />

    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #dddddd;
            text-align: left;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trade&Deal Hub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            <div class="text-center">
                <nav>
                    <h2>User Table</h2>

                    <table border="1">
                        <tr>
                            <th>Id</th>
                            <th>Name</th>
                            <th>Avatar</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Password</th>
                            <th>Id Role</th>
                        </tr>
                        <!-- Replace the data below with your actual data -->
                        <tr>
                            <td>user.Id</td>
                            <td>user.Name</td>
                            <td>user.Avatar</td>
                            <td>user.Username</td>
                            <td>user.Email</td>
                            <td>user.Password</td>
                            <td>user.IdRole</td>
                        </tr>
                        <!-- Add more rows as needed -->

                    </table>
                </nav>

                <nav>
                    <form method="post" asp-controller="Admin" asp-action="UpdateProfile">
                        <label for="name">Name:</label>
                        <input type="text" id="name" name="name" />
                        <label for="email">Email:</label>
                        <input type="text" id="email" name="email" />
                        <button type="submit">Update</button>
                    </form>
                </nav>

                <nav>
                    <form method="post" asp-controller="Admin" asp-action="ChangePassword">
                        <label for="password">Password:</label>
                        <input type="password" id="password" name="password" />
                        <label for="confirmPassword">Confirm Password:</label>
                        <input type="password" id="confirmPassword" name="confirmPassword" />
                        <button type="submit">Update</button>
                    </form>
                </nav>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Trade&Deal Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>