WebClient2/Controllers/DepositsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Business;
using Business.Models;
using WebClient2.Services;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using DataAccess.DAO;
using DataAccess.Library;
using WebClient2.BackGroundServices;
using WebClient2.ViewModel;

namespace WebClient2.Controllers
{

    [ServiceFilter(typeof(SemaphoreActionFilter))]
    [Authorize(Roles = "Admin,User")]
    public class DepositsController : Controller
    {
        private readonly IVnPayService _vpnPayService;
        public DepositsController(IVnPayService vnPayServices)
        {
            _vpnPayService = vnPayServices;
        }

        // GET: Deposits/Create
        public IActionResult Create()
        {
            if (HttpContext.Session.GetInt32("Account") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int account_id = HttpContext.Session.GetInt32("Account").Value;
            return View();
        }

        #region VNPAY
        [HttpPost]
        public IActionResult VnPay(DepositModel deposit)
        {
            if (HttpContext.Session.GetInt32("Account") == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int account_id = HttpContext.Session.GetInt32("Account").Value;
            if (ModelState.IsValid)
            {
                string id = Gencode.GenerateCodeDeposit();
                var vnPayModel = new VnPaymentRequestModel
                {
                    Amount = deposit.amount,
                    CreatedDate = DateTime.Now,
                    Description = deposit.description == null ? "" : deposit.description,
                    Id = id,
                };
                return Redirect(_vpnPayService.CreatePaymentUrl(HttpContext, vnPayModel));
            }
            return RedirectToAction(nameof(Create));
        }

        public IActionResult PaymentFail()
        {
            return View();
        }

        public IActionResult PaymentSuccess()
        {
            return View();
        }

        public IActionResult PaymentCallBack()
        {
            if (Request.Query.Count == 0)
            {
                TempData["Message"] = $"Lỗi thanh toán VN Pay"; return RedirectToAction("PaymentFail");
            }

            var response = _vpnPayService.PaymentExecute(Request.Query);
            try
            {


                if (response == null || response.VnPayReponseCode != "00") // Gia tri 00 la thanh cong
                {
                    TempData["Message"] = $"Lỗi thanh toán VN Pay: {response.VnPayReponseCode}";
                    return RedirectToAction("PaymentFail");
                }
                int user_id = HttpContext.Session.GetInt32("Account").Value;
                //Lưu đơn hàng cho Database
                Deposit d = new Deposit
                {
                    id = response.OrderId,
                    wallet_id = WalletDAO.GetWalletByAccountId(user_id).id,
                    amount = response.Amount,
                    status = StatusEnum.HOAN_THANH,
                    state = StateEnum.THANH_CONG,
                    description = response.OrderDescription,
                    create_by = user_id,
                    create_at = DateTime.Now,
                    update_by = user_id,
                    update_at = DateTime.Now,
                };
                DepositDAO.CreateDeposit(d);
                WalletDAO.UpdateWalletDepositBalance(d.wallet_id, d.amount);

                TempData["Message"] = $"Thanh toán VN Pay thành công";
                return RedirectToAction("PaymentSuccess");
            }
            catch (Exception ex) { TempData["Message"] = $"Lỗi thanh toán VN Pay: {response.VnPayReponseCode}"; return RedirectToAction("PaymentFail"); }

        }
        #endregion
    }
}

WebClient2/Controllers/WithdrawalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Business;
using Business.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using WebClient2.BackGroundServices;
using WebClient2.ViewModel;
using DataAccess.DAO;
using DataAccess.Library;

namespace WebClient2.Controllers
{
    [ServiceFilter(typeof(SemaphoreActionFilter))]
    [Authorize(Roles = "Admin,User")]
    public class WithdrawalsController : Controller
    {
        public IActionResult List()
        {
            int account_id = HttpContext.Session.GetInt32("Account").Value;

            List<Withdrawal> withdrawals = WithdrawalDAO.GetAllWithdrawalByWalletId(WalletDAO.GetWalletByAccountId(account_id).id);
            return View(withdrawals);
        }
        // GET: Withdrawals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Withdrawals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(WithdrawalModel withdrawal)
        {
            int account_id = HttpContext.Session.GetInt32("Account").Value;
            if (ModelState.IsValid)
            {
                if (withdrawal.amount + 500 <= WalletDAO.GetWalletByAccountId(account_id).balance)
                {
                    WalletDAO.UpdateWalletWithdrawalBalance(WalletDAO.GetWalletByAccountId(account_id).id, withdrawal.amount+ 500);
                    Withdrawal w = new Withdrawal
                    {
                        id = Gencode.GenerateCodeWithdrawal(),
                        wallet_id = WalletDAO.GetWalletByAccountId(account_id).id,
                        amount = withdrawal.amount,
                        bank_number = withdrawal.bank_number,
                        bank_user = withdrawal.bank_user,
                        bank_name = withdrawal.bank_name,
                        create_by = account_id,
                        update_by = account_id,
                    };

                    WithdrawalDAO.CreateWithdrawal(w);

                }
                else
                {

                    TempData["Message"] = $"Không đủ tiền thanh toán";
                    return RedirectToAction(nameof(Create));

                }

            }
            return View(withdrawal);
        }

    }
}

WebClient2/Views/Shared/_Layout.cshtml
@using DataAccess.DAO;
@{
    var account_id = ViewContext.HttpContext.Session.GetInt32("Account");
}
<style>
    .login-register-nav {
        display: flex;
        justify-content: space-between; /* Hoặc sử dụng 'space-around' để phân bổ khoảng trống */
        align-items: center; /* Đảm bảo các items được căn giữa theo chiều dọc */
    }
</style>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Trade&DealHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebClient2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Trade&Deal Hub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (account_id != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" asp-area="" asp-controller="IntermediateOrders" asp-action="Market" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Quản lý thanh toán
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Deposits" asp-action="Create">Nạp tiền</a></li>
                                    @*  <li><a class="dropdown-item" asp-area="" asp-controller="Withdrawal" asp-action="Create">Lịch sử giao dịch</a></li>*@
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Withdrawals" asp-action="Create">Yêu cầu rút tiền</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Withdrawals" asp-action="List">Lịch sử rút tiền</a></li>
                                </ul>
                            </li>
                        }
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" asp-area="" asp-controller="IntermediateOrders" asp-action="Market" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Chợ Trung Gian
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" asp-area="" asp-controller="IntermediateOrders" asp-action="Market">Chợ Trung Gian</a></li>
                                @if (account_id != null)
                                {
                                    <li><a class="dropdown-item" asp-area="" asp-controller="IntermediateOrders" asp-action="OrderSell">Đơn đã tạo</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="IntermediateOrders" asp-action="OrderBuy">Đơn đã mua</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="IntermediateOrders" asp-action="Create">Tạo đơn trung gian</a></li>
                                }
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            @if (account_id == null)
                            {
                                <div class="login-register-nav">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Đăng Nhập</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Register">Đăng ký</a>
                                </div>
                            }
                            else
                            {
                                <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Account" asp-action="Profile" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    @AccountDAO.GetAccountWithId(account_id).name
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Profile" asp-route-id="@account_id">Thông tin</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Wallet" asp-route-id="@account_id">Ví</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Logout">Đăng Xuất</a></li>
                                </ul>


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Wallet">Balance: @WalletDAO.GetWalletByAccountId(account_id.Value).balance</a>
                            </li>
                            }
                        </li>
                        @if (account_id != null && AccountDAO.GetAccountWithId(account_id).role_id == 1)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" asp-area="" asp-controller="Account" asp-action="Profile" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Quản lý Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="InterOrderManage">Quản lý đơn trung gian</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="DepositManage">Quản lí đơn nạp</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="WithdrawalManage">Quản lí đơn rút</a></li>
                                    <li><a class="dropdown-item" asp-area="" asp-controller="Admin" asp-action="UserManage">Quản lí người dùng</a></li>
                                </ul>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Trade&Deal Hub - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>